// Package responses provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package health

// Defines values for GetHealthResponseStatus.
const (
	UP GetHealthResponseStatus = "UP"
)

// GetHealthResponse defines model for GetHealthResponse.
type GetHealthResponse struct {
	Status GetHealthResponseStatus `json:"status"`
}

// GetHealthResponseStatus defines model for GetHealthResponse.Status.
type GetHealthResponseStatus string
